# Generated by Django 6.0.4 on 2026-04-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveIntegerField()),
                ('manzil', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=5)),
                ('manzil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maktab')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=56)),
                ('familiya', models.CharField(max_length=56)),
                ('otasini_ismi', models.CharField(blank=True, max_length=56, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('birth_date', models.DateField()),
                ('last_attend', models.DateTimeField(verbose_name='oxirgi marta darsga kelgan vaqt')),
                ('gender', models.BooleanField(choices=[(True, 'Erkak'), (True, 'Ayol')])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('sinf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sinf')),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='FIO')),
                ('age', models.PositiveIntegerField(default=20)),
                ('position', models.CharField(choices=[('MMBIDO', 'manaviyat va marifat ishlari boyicha direktor orinbosari'), ('teach', 'oqtuvchi'), ('Dir', 'direktor')], max_length=10)),
                ('yonalish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fanlar')),
            ],
        ),
        migrations.AddField(
            model_name='sinf',
            name='kurator',
            field=models.ForeignKey(limit_choices_to={'position': 'teach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.xodim'),
        ),
    ]
